# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://ten-ten-v2.vercel.app/sign-in")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.ID, "phoneNumber").send_keys("0901235456")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.XPATH, "//label/input").click()
    self.driver.find_element(By.XPATH, "//div[2]/label/input").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Login\')]").click()
	time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".mt-3").click()
	time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, "path").click()
	time.sleep(5)
    assert self.driver.find_element(By.CSS_SELECTOR, ".-top-2").text == "0"
  
  def test_test21(self):
    self.driver.get("https://ten-ten-v2.vercel.app/sign-in")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.ID, "phoneNumber").send_keys("0901235456")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.XPATH, "//label/input").click()
    self.driver.find_element(By.XPATH, "//div[2]/label/input").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Login\')]").click()
	time.sleep(5)

    self.driver.find_element(By.CSS_SELECTOR, ".mt-3").click()
	time.sleep(5)

    self.driver.find_element(By.CSS_SELECTOR, "path").click()
	time.sleep(5)

    assert self.driver.find_element(By.CSS_SELECTOR, ".-top-2").text == "0"
    self.driver.find_element(By.LINK_TEXT, "Log Out").click()
	time.sleep(5)

    self.driver.find_element(By.ID, "phoneNumber").send_keys("02608555691")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.XPATH, "//label/input").click()
    self.driver.find_element(By.XPATH, "//div[2]/label/input").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Login\')]").click()
	time.sleep(5)

    self.driver.find_element(By.LINK_TEXT, "Leave Registration").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'+ Add leave\')]").click()
	time.sleep(5)

    self.driver.find_element(By.XPATH, "//div[2]/div[2]/div").click()
    self.driver.find_element(By.XPATH, "//tr[2]/td[4]/div").click()
    self.driver.find_element(By.XPATH, "//div[3]/div[2]/div").click()
    self.driver.find_element(By.XPATH, "//div[3]/div[2]/div/input").send_keys("2023-12-07")
    self.driver.find_element(By.XPATH, "//input[@type=\'text\']").send_keys("Nghỉ ốm - Sang automation test")
	time.sleep(5)

    self.driver.find_element(By.XPATH, "//span[contains(.,\'Submit\')]").click()
	time.sleep(5)

    self.driver.find_element(By.LINK_TEXT, "Log Out").click()
    self.driver.find_element(By.ID, "phoneNumber").send_keys("0901235456")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.XPATH, "//label/input").click()
    self.driver.find_element(By.XPATH, "//div[2]/label/input").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Login\')]").click()

	time.sleep(5)

    self.driver.find_element(By.CSS_SELECTOR, ".mt-3").click()
	time.sleep(5)

    assert self.driver.find_element(By.CSS_SELECTOR, ".-top-2").text == "1"
	time.sleep(5)

    self.driver.find_element(By.CSS_SELECTOR, "path").click()
  
